### ISSUE TITLE
Python 3, galaxyproject.galaxy update, and yaml config

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/usegalaxy-playbook#206]
I've updated galaxyproject.galaxy to the latest version and switched Test to use a YAML config. This issue is mainly so that I don't forget a few outstanding issues that I can't work on until next week.

1. See the FIXME comments in 22bac9f3328ac3a81d65c189c267b81aae917454. I haven't run the config playbook on Main but I *think* it should be ok. Remaining issues are due to the yaml conversion.
2. The role can't write Test's uWSGI config properly due to ordering problems, see galaxyproject/ansible-galaxy#66. Test's `galaxy.yml` is currently modified by hand to get it running, don't run the config playbook on Test until this is fixed.
3. Handlers are not running because of galaxyproject/pulsar#172 issue, which will require a pulsar-galaxy-lib release followed by a Galaxy requirements release.

Test's `uwsgi` section for reference:

```yaml
uwsgi:
    # thought I needed this but I don't, error on uwsgi start was due to ordering, not a lack of socket option
    #socket: 127.0.0.1:0
    master: true
    processes: 8
    threads: 4

    single-interpreter: true
    thunder-lock: true
    harakiri: 600
    buffer-size: 16384

    log-maxsize: 134217728
    log-master-bufsize: 15865856

    pythonpath: lib
    module: galaxy.webapps.galaxy.buildapp:uwsgi_app_factory()

    plugins-dir: /cvmfs/test.galaxyproject.org/deps/_conda/envs/_galaxy_/lib/uwsgi/plugins
    plugin: spinningfifo

    zerg: /srv/galaxy/test/var/zergpool.sock

    master-fifo: /srv/galaxy/test/var/zerg-new.fifo
    master-fifo: /srv/galaxy/test/var/zerg-run.fifo
    master-fifo: /srv/galaxy/test/var/zerg-old.fifo

    if-exists: /srv/galaxy/test/var/zerg-run.fifo
    hook-accepting1-once: writefifo:/srv/galaxy/test/var/zerg-run.fifo 2q
    endif:
    hook-accepting1-once: spinningfifo:/srv/galaxy/test/var/zerg-new.fifo 1
```

**TODO**
- [ ] Fix `galaxyproject.galaxy`'s `galaxy_remote_users` and `galaxy_become_users`
- [x] Fix `galaxyproject.galaxy` to write an ordered `uwsgi` section and support uWSGI control blocks
- [x] Pulsar fix for handlers
- [ ] Dynamic options bug fix
- [x] Fix hacking to conda activate

**Comment by natefoo** [comment]
I forgot the most important issue: terrible, terrible hacking to Test's conda `activate` script. `activate` is one global script symlinked in to envs. Running `nodeenv` in the `_galaxy_` env wrote to that script (!) and what it wrote causes the base env to be placed on the front of `$PATH` (ahead of the env!). It also caused yarn to be installed in the base env.

Things to investigate:

1. Is this still a problem with newer versions of Conda that don't use activate (Test still runs 4.3.34)?
2. The `_galaxy_` env is not using conda-forge virtualenv, would using virtualenv fix it?
3. ???

Also one last issue: `certifi` is part of a basic Python env in Conda, and it is also a pinned Galaxy dependency. If the versions differ, pip will attempt to update it and then refuse when it realizes it is not managed by pip. Workaround for this would be good. I think Galaxy should be able to run without a virtualenv.

**Comment by natefoo** [comment]
The `activate` problems have been worked around by using a virtualenv built off the `_galaxy_` env's Python (as is done in `common_startup.sh`). I was hoping to remove this extra layer of isolation since Conda already provides it, but the problems above necessitate it.

Test's uWSGI config is now being written properly with an update to `galaxyproject.galaxy`.

pulsar-galaxy-lib 0.9.0 has been released and handlers are running now. There are problems with some (all?) tools that use dynamic options such as bowtie2:

```pytb
galaxy.jobs.runners.pulsar ERROR 2019-04-16 15:26:26,628 failure running job 1017274
Traceback (most recent call last):
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/util/__init__.py", line 1012, in unicodify
    value = str(value)
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.6/site-packages/Cheetah/Template.py", line 1053, in __unicode__
    return getattr(self, mainMethName)()
  File "cheetah_DynamicallyCompiledCheetahTemplate_1555443583_0915494_96112.py", line 261, in respond
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.6/site-packages/Cheetah/NameMapper.py", line 288, in valueFromSearchList
    executeCallables=executeCallables)
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.6/site-packages/Cheetah/NameMapper.py", line 231, in _valueForName
    if executeCallables and hasattr(nextObj, '__call__') and \
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/tools/wrappers.py", line 138, in __getattr__
    self._fields[name] = self._input.options.get_field_by_name_for_value(name, self._value, None, self._other_values)
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/tools/parameters/dynamic_options.py", line 658, in get_field_by_name_for_value
    assert field_name in self.columns, "Requested '%s' column missing from column def" % field_name
AssertionError: Requested '__call__' column missing from column def

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/pulsar.py", line 350, in __prepare_job
    job_wrapper.prepare(**prepare_kwds)
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/jobs/__init__.py", line 871, in prepare
    self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/tools/evaluation.py", line 451, in build
    raise e
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/tools/evaluation.py", line 447, in build
    self.__build_command_line()
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/tools/evaluation.py", line 472, in __build_command_line
    command_line = fill_template(command, context=param_dict)
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/util/template.py", line 18, in fill_template
    return unicodify(Template(source=template_text, searchList=[context]))
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/util/__init__.py", line 1018, in unicodify
    msg = "Value '%s' could not be coerced to Unicode" % value
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.6/site-packages/Cheetah/Template.py", line 1053, in __unicode__
    return getattr(self, mainMethName)()
  File "cheetah_DynamicallyCompiledCheetahTemplate_1555443583_0915494_96112.py", line 261, in respond
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.6/site-packages/Cheetah/NameMapper.py", line 288, in valueFromSearchList
    executeCallables=executeCallables)
  File "/cvmfs/test.galaxyproject.org/venv/lib/python3.6/site-packages/Cheetah/NameMapper.py", line 231, in _valueForName
    if executeCallables and hasattr(nextObj, '__call__') and \
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/tools/wrappers.py", line 138, in __getattr__
    self._fields[name] = self._input.options.get_field_by_name_for_value(name, self._value, None, self._other_values)
  File "/cvmfs/test.galaxyproject.org/galaxy/lib/galaxy/tools/parameters/dynamic_options.py", line 658, in get_field_by_name_for_value
    assert field_name in self.columns, "Requested '%s' column missing from column def" % field_name
AssertionError: Requested '__call__' column missing from column def
```

I am not sure yet what's causing that.
