### ISSUE TITLE
Genome Additions Master Ticket

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#242]
# Genome and indexes for CVMFS and http://usegalaxy.org

**CONVERT THIS ISSUE TO A PROJECT** @jennaj

> This list changes over time as new data sources are targetted for indexing and user requests are considered. See posts below for genome batches completed and in progress.

Current plans are to bring http://usegalaxy.org up to date with UCSC's released genomes, indexed for all tools, so those do not need to be requested by users at this time.

Main:
 - [ ] Automate index creation on Main https://github.com/galaxyproject/usegalaxy-playbook/issues/38 

Other reference data:
- [ ] https://github.com/galaxyproject/galaxy/issues/1470#issuecomment-220096290 - Add hg38 MAF
- [ ] https://github.com/galaxyproject/usegalaxy-playbook/issues/80 - Update Kraken databases
- [ ] https://github.com/galaxyproject/tools-devteam/issues/390 -Update SICER to include more genome builds (ideally all on the instance). Not an indexing/DM issue exactly, but _should it be_?

Admin/Local Data and DM usage enhancements are included here.  
- [ ]  https://github.com/galaxyproject/galaxy/issues/1471 -Methods to manage genomes, Admin enhancement ideas
- [ ]  https://github.com/galaxyproject/galaxy/issues/1516 -Sort view by dbkey _Admin -> Local Data -> View Tool Data Table_ Entries
- [ ]  https://github.com/galaxyproject/galaxy/issues/1518 -Add dbkey to report and sort by it in _Admin -> Local Data -> View Data Manager Jobs_
- [ ]  https://github.com/galaxyproject/tools-devteam/issues/319 -Modify Bowtie2 DM so that it will not create duplicates when "Include Tophat2" is used
- [ ]  https://github.com/galaxyproject/tools-iuc/issues/530 -HISAT2 Data manager reports unrecognized arguments for _SNP annotation_
- [ ] https://github.com/galaxyproject/galaxy/issues/1904 -LiftOver DM request

Resolved data issues:
 - [x] Some indexes are associated with new tools part of https://github.com/galaxyproject/tools-iuc/issues/488
- [x]  https://github.com/galaxyproject/galaxy/issues/1679 -Track promotion of Kraken reference data to http://usegalaxy.org
- [x] https://github.com/galaxyproject/galaxy/issues/3096 -Add more genomes to SnpEff
- [x] https://github.com/galaxyproject/galaxy/issues/2128 -Restore Fetch Taxonomic Rep tool to http://usegalaxy.org. Closed - Use Kraken instead.
- [x]  https://github.com/galaxyproject/galaxy/issues/1885 -Fetch Fasta DM config issue
- [x] https://github.com/galaxyproject/galaxy/issues/2530 -Add in latest dbkey to builds.txt
- [x] https://github.com/galaxyproject/galaxy/issues/2922 -Improve UI admin access to locally cached data index files

**New genomes and indexes will be installed at https://test.galaxyproject.org/ first for testing**. If your genome is listed and checked as complete, community testing and feedback can be posted to https://biostar.usegalaxy.org or through a bug report from the error dataset (from a mapping tool, etc).

All data will later be promoted to http://usegalaxy.org. Timeline is not firm.
- [x] **Indexes Galaxy Main April 2016**. https://github.com/galaxyproject/galaxy/issues/1470#issuecomment-208442266
- [ ] **Indexes Galaxy Main 2018**. https://github.com/galaxyproject/galaxy/issues/1470#issuecomment-208444904

# Making a Reference genome request
- Create reply below
- Be specific
  - Name of organism, including common "key" used
  - Exact source. Ex: UCSC (dbkey), NCBI project ID, other URL
  - Build details: include mito, chloro, plasmids, etc.
  - All indexes are now generated for brand new genomes by default. Or pick one of: "All" "Bowtie2" "MyFavTool" if your genome is at http://usegalaxy.org, but not available in your tool of interest
  - **Don't forget anyone can add and use a custom genome right now with most tools - no waiting!** https://wiki.galaxyproject.org/Learn/CustomGenomes

**Comment by jennaj** [comment]
Request: 

Genome: Citrus sinensis v1.1

Source: https://www.citrusgenomedb.org/bio_data/79

**Comment by jennaj** [comment]
Request:

Human herpesvirus 1 with ref accession number NC_001806

**Comment by jennaj** [comment]
Request:

Genome: Tribolium castaneum genome assembly (Tcas5.2)

Source: https://www.ncbi.nlm.nih.gov/genome?term=tribolium%20castaneum

**Comment by jennaj** [comment]
Request:

Dada tools: https://github.com/galaxyproject/usegalaxy-playbook/issues/273

**Comment by echoyps** [comment]
Dear Galaxy Team,

It would be great if the genome and annotation release of Physcomitrella patens can be added to Galaxy Main.

They are available at NCBI:
https://www.ncbi.nlm.nih.gov/genome/383
https://www.ncbi.nlm.nih.gov/genome/annotation_euk/Physcomitrella_patens/100

Best,
Peishan

**Comment by jennaj** [comment]
@echoyps & everyone else with genome requests:

We will now be adding new genomes over the next few months and throughout the upcoming year. Please continue to post requests here. UCSC and NCBI are the preferred data sources. Others are possible. However requested, be specific.

**Reminders:** 

Anyone can use genome (or transcriptome/exome) `fasta` data as a custom genome "from the history" now -- you do not need to wait for us to index server-side. Annotation is supplied by the end-user from the history by default (even for built-in indexed genomes) -- with just a few tool exceptions, but those also accept annotation data from the history. Genomes (`fasta`) are the data that is currently indexed server-side. Annotation may be indexed in the future. Custom genomes (`fasta`) can be promoted to a custom build (_User > Custom Builds_) in order to create a custom "database" metadata key that can be assigned to datasets (some tools wrapped for Galaxy require that the "database" is assigned to inputs). 

**Be sure to format the genome `fasta` correctly (remove description content on the ">" title line) and make sure the genome build/version and chromosome identifiers are an _exact match_ between the custom reference genome (`fasta`) and any reference annotation (`gtf` or `gff3`) you plan to use in your analysis, before starting any analysis that uses it or promoting the `fasta` to a custom build.** This will avoid problems later on. If there is a formatting problem (example: headers on a `gtf` dataset) or chromosome mismatch issue between inputs, this usually requires the need to fix the `fasta` format and start the analysis over from the very start, which can be frustrating. If you have a choice about annotation formats, choose the `gtf` version instead of the `gff3` version -- a `gtf` formatted annotation dataset is accepted by more tools, and using the same exact annotation data throughout an analysis workflow is very important.

Mapping jobs will usually not "fail" due to chromosome identifier mismatch issues. Instead, if the annotation is input during the mapping step, the annotation will not really be used, creating problematic scientific results that may not be obvious to detect. Tools used downstream with a mismatched genome+annotation can also produce problematic scientific results that are not obvious, or may fail outright with errors that are difficult to interpret. Problematic annotation formatting itself will also lead to problems. Try to avoid issues by preparing your inputs correctly at the start :)

Finally, when loading these data with the `Upload` tool, allow the datatype to be detected instead of assigning it. This triggers basic format checks and a Galaxy-assigned datatype. If you do not get the expected datatype assigned, this almost always means that there is a formatting issue that needs to be addressed. Most format issues can be resolved within Galaxy. After fixed, the correct datatype can be assigned: Click on the dataset's pencil icon > Edit Attributes forms > Datatypes tab > "detect datatype" (best choice) or directly assigned (be careful if choosing this option). If Galaxy cannot "detect" the format correctly, there is likely still a data content or format problem.

If you ever have a problem that you cannot figure out how to resolve, know that the vast majority of tool errors or unexpected results are due to input issues that can be fixed to achieve a successful and correct scientific/technical result. First, review the _tool form help_ -- most have examples of the expected input's content and format. Next, review our _Troubleshooting and other FAQs_. If those do not resolve the issue, the _Galaxy Help forum_ is a great place to review prior Q&A or to ask a novel question. The _Galaxy Training Network (GTN) tutorials_ are also a very useful resource -- compare your methods to the examples. 

I'm only posting this advice here now since it hasn't been covered for a while at Github, and there are newer related FAQs plus prior Q&A available. Any followup/clarification should be asked about at _Galaxy Help_ (not here).  

**The FAQs/links below will help with all of the above.** 

**All FAQs:** https://galaxyproject.org/support/ 

Start with these to learn how to use a custom genome and the associated annotation:
* [Common datatypes explained](https://galaxyproject.org/learn/datatypes/)
* [Preparing and using a Custom Reference Genome or Build](https://galaxyproject.org/learn/custom-genomes/)
* [Mismatched Chromosome identifiers (and how to avoid them)](https://galaxyproject.org/support/chrom-identifiers/)
* [Extended Help for Differential Expression Analysis Tools](https://galaxyproject.org/support/diff-expression/) -- formatting help included usually applies across tools and analysis goals, not just DE analysis, and whether the analysis is executed in Galaxy or otherwise.

Error or unexpected result FAQ:
* [My job ended with an error. What can I do?](https://galaxyproject.org/support/tool-error/)

Galaxy Help forum:
* https://help.galaxyproject.org/
* Troubleshooting post: https://help.galaxyproject.org/t/troubleshooting-resources-for-errors-or-unexpected-results/42

GTN Tutorials:
* https://training.galaxyproject.org/

Thanks! Jen

**Comment by dram26** [comment]
Hi!

could you kindly add macaca fascicularis genome for BWA ? it's now at ncbi https://www.ncbi.nlm.nih.gov/genome/776 

[There is a 2015 petition for the same here https://trello.com/c/mJWnAuuQ/1511-reference-genome-requests-for-http-usegalaxyorgby AmyK Feb 4, 2015 at 6:47 PM and another in 2016, but i guess the source wasn't validated then? ]

Best! David
