### ISSUE TITLE
Issues with main

### ISSUE THREAD

**Issue by jxtx** [galaxyproject/usegalaxy-playbook#250]
# Data issues

- [x] Problems with builds, references, etc that prevent tools from working on main. @jennaj @davebx @natefoo @blankenberg @martenson all contributed. https://github.com/galaxyproject/usegalaxy-playbook/issues/55

- [ ] Automate building reference data in CVMFS https://github.com/galaxyproject/usegalaxy-playbook/issues/38 @natefoo @jennaj

 - [ ] DM for UCSC liftOver data, impacts **Batch Coordinate Convert** tool  galaxyproject/galaxy#1904

- [x] **Extract Genomic DNA** needs tool update to be data table aware @davebx https://github.com/galaxyproject/galaxy/issues/5493. Update: tool removed from distro, IUC version update in MTS ready for usegalaxy.org install/update, tested and works at usegalaxy.eu. Tracked here https://github.com/galaxyproject/galaxy/issues/5493#issuecomment-375838559

# Tools that don't work

- [ ] Regular tool updates @davebx @erasche 
- [ ] Tools installed in a CVMFS volume and shared @natefoo @afgane @erasche 
- [ ] Automate tool installation on main @natefoo @afgane 
- [ ] Automate tool data management as well @natefoo @afgane @davebx 
- [ ] Stream stdout/stdin so users can see errors before jobs finish (Pulsar too) @natefoo 
- [x] Planemo test against running Galaxy instance https://github.com/galaxyproject/ephemeris/issues/76

# Make it easier for people to diagnose problems

Need more Galaxy team members to help maintain main.

- [x] Document current Main infrastructure (hosts, etc.) @natefoo 
- [ ] "Buddy up" on fixing problems

# Better resource utilization

- [x] Jetstream scaling @natefoo 
- [x] Make a metric that polls the mem usage from cgroups so we can actually see what tools use related: galaxyproject/galaxy#4862 @natefoo 

# Pulsar

- [x] Pulsar issues galaxyproject/pulsar#75 galaxyproject/pulsar#129 galaxyproject/pulsar#135 galaxyproject/pulsar#150 galaxyproject/pulsar#151

# Automated Testing 

- [ ] Jupyter
- [ ] Trackster 
- [ ] Common workflows
- [ ] Popular tools
- [ ] Training exercises
