### ISSUE TITLE
Genomespace ending on 11/15 -- updates to Main & communications

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#258]
GenomeSpace is ending on 11/15

**_To-do items re servers + galaxyproject.org hub_**

- [ ] Remove on 11/15 (am/early) **GS importer/exporter tools** from usegalaxy.org (entirely, not just hidden) -- who?
- [ ] Remove on 11/15 (am/early) **GS Open ID** from usegalaxy.org -- who?
- [ ] Update on 11/15 (am/early) **GS references in Hub** to note the phase-out date (past tense), link to Ghelp post, and remove any detailed "how-to" info @jennaj will start a PR branch, all can contribute
- [ ] Other **usegalaxy.* servers** should probably do the same. Ping @bgruening @Slugger70 @frederikcoppens
- [ ] Mark as deprecated on 11/15 **GS importer/exporter tools in ToolShed repos + linked Github** (??) -- who?
- [ ] Find out which specific accounts at .org have a GS Open ID. Including "last login" date and account status (active/deleted/purged) in tab file.* See details below. **We should do this soon.** -- who?

* Count how many .org users are GS users active vs current vs recent (last few years) vs in the long-long ago vs no longer used ("deleted" will contain some that are actively resolving dups or haven't noticed dups were suspended yet). Once we know the number of active/prior GS users we can determine if galaxy-announce should NOT be emailed (per @tnabtaf [comments here](https://github.com/galaxyproject/usegalaxy-playbook/issues/258#issuecomment-539671853)) and instead email (bcc) just those users with a GS Open ID at org. 
* [Small concern](https://github.com/galaxyproject/usegalaxy-playbook/issues/258#issuecomment-539677713) from @jennaj that targetting this way will not reach everyone but may be good enough. Gitter/Galaxy Help + "heads up" email to galaxy-public-servers can fill in the blanks (probably). Other public servers could do the same kind of targetted email for their GS users if they want to.

**_To-do items re communications_**

- [ ] Draft message to Galaxy users about the upcoming changes @jennaj @tnabtaf @blankenberg and whoever else wants to contribute from org + usegalaxy.* servers
- [ ] Actually post/email* on 10/15 (month notice)
- [ ] Reminder post/email* on 11/8 (week notice)
- [ ] If users have questions after that, we redirect to the GHelp post.

* Post to:
  * Galaxy Help
  * Gitter (~~which channels? Just primary?~~) https://gitter.im/galaxyproject/Lobby && possibly https://gitter.im/galaxyproject/admins)
  * Email to ~~galaxy-announce~~ Based on .org stats (TBD), instead consider only emailing .org users with GS OpenID attached to account
  * Email to galaxy-dev? **Feedback Please**
  * Email any others? Ex: galaxy-public-servers. Heads up about changes/plans that .org will be doing? **Feedback Please**
  * Possibly email to GS list (coordinate with them so is accepted) @jennaj can ask them if we want this. **Feedback Please**

Any and all feedback welcome

**Comment by tnabtaf** [comment]
A couple of comments

* I would be against a separate email to galaxy-announce (~11,000 members). What percentage will care?
* Can we identify and email only account holders on main that have interacted with GenomeSpace?
* +1 for Gitter (main channel) and GHelp post. Can also include in November newsletter.

**Comment by jennaj** [comment]
@tnabtaf 

* Agree, less spam-ish. But would limit the next item for .org users, not all Galaxy users (working on locals, cloud, other public server users, etc). 
* Identify/email users that actually have a GS OpenID attached to their account at .org? The GS OpenID is required to actually use the GS tools (import or export).
* Super. We can draft out the gitter notices when we do the primary and "update" emails.

**Comment by blankenberg** [comment]
Just a small bump to confirm that GenomeSpace servers have been shutdown: http://genomespace.org/

**Comment by jennaj** [comment]
Appears to be gone now. I was just updating our FAQs. Including this one: https://galaxyproject.org/support/loading-data/

The importer/exporter tools still need to be removed from the tool panel at https://usegalaxy.org. Guessing that we won't remove the OpenID functionality until the `20.01` update? https://docs.galaxyproject.org/en/master/releases/19.09_announce.html#genomespace

Not sure what we want to do for the ToolShed (mark the tools as deprecated?)

Not sure if we need/want to do anything else. It has been 5 days and no one has asked about it. Maybe just alert other public server admins? At Gitter? Or they can read about it in the release notes...

**Comment by jennaj** [comment]
Closing
