### ISSUE TITLE
Data fixes to-do summarized

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#55]
- [x] Once all data items completed, snapshot CVMFS.
 - [x] Close out Road map item https://github.com/galaxyproject/galaxy/issues/5474

----
1. **dbkey duplicates** are showing up in Upload and Edit Attributes.  Related to builds/len updates for UCSC genomes. See https://github.com/galaxyproject/galaxy/issues/2530 & https://github.com/galaxyproject/galaxy/issues/2884.

**Fix1 DM fetch dup commented out (*aptMan1*)**

 - [x] **Fix1** Commented out duplicated dbkeys between manual vs builds.txt content. *UCSC builds updates weekly now, unlikely to present as a process conflict in future*
> $  cat /galaxy-repl/test/tool_data/toolshed.g2.bx.psu.edu/repos/devteam/data_manager_fetch_genome_dbkeys_all_fasta/776bb1b478a0/dbkeys.loc
> #<dbkey>		<display_name>	<len_file_path>
hg19_rCRS_pUC18_phiX174	Homo sapiens (hg19 with mtDNA replaced with rCRS, and containing pUC18 and phiX174) (hg19_rCRS_pUC18_phiX174)	/galaxy-repl/manageddata/data/hg19_rCRS_pUC18_phiX174/len/hg19_rCRS_pUC18_phiX174.len
> #aptMan1	Brown Kiwi Jun. 2015 (MPI-EVA AptMant0/aptMan1) (aptMan1)	/galaxy-repl/manageddata/data/aptMan1/len/aptMan1.len
 - [x] **Fix1** Integration tested on test (working data)
 - [x] **Fix1** Push fix to cvmfs
 - [x] **Fix1** Integration tested on main (published cvmfs data)

**Fix2 Manual dbkey dups need to be commented out *rn6* and *danRer10***

 - [x] **Fix2** Comment the two lines in a file owned by @natefoo 
> $ cat /cvmfs/data.galaxyproject.org/managed/location/byhand_dbkeys.loc
> #<dbkey>		<display_name>	<len_file_path>
> rn6	Rat Jul. 2014 (RGSC 6.0/rn6) (rn6)	/cvmfs/data.galaxyproject.org/managed/len/rn6.len
> danRer10	Zebrafish Sep. 2014 (GRCz10/danRer10) (danRer10)	/cvmfs/data.galaxyproject.org/managed/len/danRer10.len
 - [x] **Fix2** Integration tested on test (working data - no change, did not present on test originally)
 - [x] **Fix2** Push fix to cvmfs
 - [x] **Fix2** Integration tested on main (published cvmfs data)

----

2. **DM 2bit indexed genomes (example: danRer10) are not found by Extract Genomic DNA**. 

 - [x] Issue created for native tool fix in distro https://github.com/galaxyproject/galaxy/issues/5493
 - [x] Update/testing tracking issue created https://github.com/galaxyproject/usegalaxy-playbook/issues/97 and linked into to-do testing list https://github.com/galaxyproject/usegalaxy-playbook/issues/86

----

3. **Missing indexes *danRer10*** (must have missed it first round, thought was done). Needed: Tophat2, HISAT2, RNA STAR: https://github.com/galaxyproject/galaxy/issues/1470#issuecomment-208442266

 - [x] Fixed - added back to index to-do list
> $ ls /galaxy-repl/manageddata/config/bowtie2_indices.loc
/galaxy-repl/manageddata/config/bowtie2_indices.loc
> $ ls /cvmfs/data.galaxyproject.org/managed/seq/ | grep danRer
danRer10.2bit
danRer10.fa
> $ ls /galaxy-repl/manageddata/data/danRer*
bowtie2_index  picard_index  sam_indexes  seq
> $ ls /galaxy-repl/manageddata/data | grep danRer
danRer10

----

4. ***papHam1* typo in the table bowtie2_indexes** (inherited into tophat2_indexes) https://github.com/galaxyproject/galaxy/issues/3604

 - [x] Fixed (@natefoo) - direct loc file typo fix in c2 of:
> $ cat /galaxy/data/location/bowtie2_indices.loc | grep papHam
> papHam1	papHam1	 Baboon (Papio anubis): papHam1 /galaxy/data/papHam1/bowtie2_index/papHam1
 - [x] Integration tested on test (working data). https://test.galaxyproject.org/u/jenjackson/h/test-history-papham1
 - [x] Push fix to cvmfs
 - [x] Integration tested on main (published cvmfs data). https://usegalaxy.org/u/jen/h/test-case-papham-papham1

----

5. ***rheMac2* and *rheMac3* have two indexes (each) listed in the tables bowtie2_indexes, tophat2_indexes**. One DM, the other from earlier. Just keep one each, per bowtie2_indexes loc, shouldn't matter which.

 - [x] Fixed - comment out duplicate lines created by running index with + without a DM.
> $ vi /galaxy/data/location/bowtie2_indices.loc
> $ grep rheMac /galaxy/data/location/bowtie2_indices.loc
> #rheMac2	rheMac2	Rhesus Macaque (Macaca mulatta): rheMac2	/galaxy/data/rheMac2/bowtie2_index/rheMac2
> #rheMac3	rheMac3	Rhesus Macaque (Macaca mulatta): rheMac3	/galaxy/data/rheMac3/bowtie2_index/rheMac3
 - [x] Integration tested on test (working data)
 - [x] Push fix to cvmfs
 - [x] Integration tested on main (published cvmfs data)

----

6. **DM fetched genomes" trigger an error with bedtools getfastabed 2.26.0.0** https://github.com/galaxyproject/usegalaxy-playbook/issues/59

 - [x] Fixed - wrapper update https://github.com/galaxyproject/tools-iuc/pull/1710
 - [x] Update test from MTS
 - [x] Integration tested on test (working data)
 - [x] Update main from MTS
 - [x] Integration tested on main (published cvmfs data)

----

@natefoo Pretty sure the rest resolved already. Thanks!

**Comment by jennaj** [comment]
**Update** - other genomes that are duplicated in the locs are also now problematic with tools. I am not sure exactly why but suspect a data path problem (the first "found" between duplicates is not the correct path to the data needed by the tool, e.g. a `.len` file).

See this test history: https://usegalaxy.org/u/jen/h/test-history-extract-indexed-genome

**Comment by jennaj** [comment]
Roadmap Q1/Q2 2018 https://github.com/galaxyproject/galaxy/projects/8

**Comment by jennaj** [comment]
Done!
