### ISSUE TITLE
Summary of issues to have GTN 16S Mothur/Metagenomics tutorial usable on Main

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#74]
Related tickets/PRs:

Active

 - [ ] To-do: 6/6 request that charts are used in the next tutorial revision to replace the Plotting tool. Needs training-repo ticket if confirmed a yes (some discussion going on).
 - [ ] Consider adding tool: Newick display to support users running GTN 16S tutorial on main https://github.com/galaxyproject/usegalaxy-playbook/issues/72. 6/6: Some discussion about whether to install or not. Is not at `eu` and not sure if in the metagenomics docker image.

Done

 - [x] Upgrade Plotting Tool version 1.0.1 to 1.0.2. Used in tutorials (v 1.0.1 does not work with it) https://github.com/galaxyproject/usegalaxy-playbook/issues/71. 6/6: Tool updated to v 1.0.2, fails test, not sure if config or tool problem, see ticket.
 - [x] Mothur Venn does not produce output with format/datatype set to "svg" https://github.com/galaxyproject/tools-iuc/issues/1643
 - [x] Mothur tools: all logfiles have datatype "txt" but some have unparsed content and are not viewable in UI https://github.com/galaxyproject/usegalaxy-playbook/issues/70
 - [x] Typo fix and clarified an input as a collection https://github.com/galaxyproject/training-material/pull/644
 - [x] Mothur Make.biom does not recognize tabular datatype dataset as "metadata" input https://github.com/galaxyproject/tools-iuc/issues/1644 **Tool needs update on usegalaxy.org & galaxy.uni-freiburg.de**, see ticket for details
 - [x] Consider adding tool: Visualize with Krona https://github.com/galaxyproject/usegalaxy-playbook/issues/73

Tutorial link https://galaxyproject.github.io/training-material/topics/metagenomics/tutorials/mothur-miseq-sop/tutorial.html

Testing history: https://usegalaxy.org/u/jen/h/16s-microbial-analysis-with-mothur---proccess

**Comment by jennaj** [comment]
Mothur update in progress: https://github.com/galaxyproject/tools-iuc/pull/1722

**Comment by jennaj** [comment]
There may be a new issue with Unique.seqs or I missed it the original testing. Will follow up on this and get it ticketed distinctly if needed/someone else does not do it first. https://github.com/galaxyproject/tools-iuc/pull/1722#issuecomment-371162927

**Comment by jennaj** [comment]
https://github.com/galaxyproject/training-material/pull/715

**Comment by jennaj** [comment]
Update: For above, a few more tests are in progress, I prioritize to wrap that all up.

**However, a bit more is needed to close this out:**

@shiltemann (tool author) notified me that there are two new tools in the updated Mothur suite that were not installed when the others were updated at Galaxy Main https://usegalaxy.org.

@davebx Could we get these installed as well? Let me know once on main and I'll do a few more quick checks to ensure install is good (tool installs plus run through the tutorial). It may be just these two: **chimera.vsearch** and **taxonomy-to-krona** but she can correct us if there are others, or perhaps just review MTS repo and get everything, so we are current. This will help with tutorial usage, plus Mothur usage in general.

_News (at least for me):_ Questions for all mirrors come into our various support channels and direct contacts for assistance. I actually didn't know main questions went to eu team.. Is sort of cool metric of sorts that galaxy users have adopted the mirror consolidation so quickly! Big win 💯

**Comment by shiltemann** [comment]
@jennaj @davebx It appears that all the tools that made their first appearance in the 1.39.5 version did not get installed. `chimera.vsearch` and `taxonomy-to-krona` are the only ones of those that are used in the tutorial, but `biom.info`, `merge.counts` and `rename.seqs` were also new in that version and not available in main currently

**Comment by jennaj** [comment]
Looks like this is still pending a full tool update to capture all in the suite. 

@davebx Know we are busy with the release but could we get to this after? Thanks!

**Comment by natefoo** [comment]
The missing Mothur tools should now be installed on usegalaxy.org, thanks for pointing them out @shiltemann.

**Comment by jennaj** [comment]
installed

- chimera.vsearch
- taxonomy-to-krona
- biom.info
- rename.seqs
- merge.count

I'll run through the new tutorial/updated tools in sequence (some already tested for in other issues) once the last two items are fixed. Or maybe sooner, those are both later/optional steps.
