### ISSUE TITLE
Testing and tool/doc updates

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#86]
# Move all of this into a Project

Note: click on labels to find all of a particular type in this repo. No tags for usage testing status (as installed/integrated on main) in the other repos, but comments are included below for test status. Not everything is captured -- this represents issues that users have reported or that were uncovered by general testing/usage. Issue order does not (usually) indicate priority/ranking.

Testing help is welcomed. **Please don't check anything off unless you have actually tested it and linked tickets/PRs get closed.** Many of these are bugs that only show up under specific conditions. We need to confirm those are resolved. Users follow these tickets, especially those that reported the bug to begin with.  

If you help test on main/eu, **you can use the test histories included in most issues to reproduce the problem and confirm fix/close ticket(s)**. Comment and ping @jennaj if you are not sure if the item should really be closed out or if you want a 2nd review. **When testing (closed out or not), please include details**: tool version, where tested (URL), alternative test history share link.. in the primary issue's comments and check it off as done in here if original problems fixed __as installed on main/eu__ (not just a dev local).

## Meta Active

- [ ] **See if the latest MACS2 presents with this issue**: https://docs.galaxyproject.org/en/master/admin/conda_faq.html#what-can-i-do-about-this-placehold-error. Example Q&A: https://biostar.usegalaxy.org/p/27086. IUC gitter abt same https://gitter.im/galaxy-iuc/iuc?at=5aa6d7db458cbde557279fe5
- [ ] Update/retest/ping everything still open at **Known issues**  vs 18.01/18.05 https://galaxyproject.org/support/tool-issues/
- [ ] **Retest/update tool updates** [listed here under issues](https://github.com/galaxyproject/usegalaxy-playbook/issues) plus add any still failed tests versus 18.05 for main/mirrors to [known issues](https://galaxyproject.org/support/tool-issues/) 

###  Main

- [ ] **Saved Histories list** -- options that don't work yet or could use tuning plus ok's https://github.com/galaxyproject/galaxy/issues/5871
- [ ]  **"Peek view" scroll** different between Chrome and Safari https://github.com/galaxyproject/galaxy/issues/6117
- [ ] **Annotate with DGI** Fix tool or remove from main? https://github.com/galaxyproject/tools-devteam/issues/504. https://github.com/galaxyproject/galaxy/projects/8#card-8100080
- [ ] **CDT** Fix tool or remove from main? https://github.com/galaxyproject/galaxy/issues/4303. https://github.com/galaxyproject/galaxy/projects/8#card-8100080
 - [ ] **Remove or tag deprecated tools** GATK https://github.com/galaxyproject/galaxy/projects/8#card-7663074 & https://github.com/galaxyproject/galaxy/issues/3607 and Cloudmap https://github.com/galaxyproject/galaxy/projects/8#card-7663634 & https://github.com/galaxyproject/galaxy/issues/4183
 - [ ] **Related - mark Cuff* tools on usegalaxy.org to align with usegalaxy.eu (deprecated)**?. https://github.com/galaxyproject/galaxy/projects/8#card-8100080
 - [ ] Align other tools? Some or all?. https://github.com/galaxyproject/galaxy/projects/8#card-8100080

###  New BAM datatypes

 - [ ] **Re-test more new bam datatypes** Do once tool produce/use these (qname_sorted.bam, qname_input_sorted.bam). https://github.com/galaxyproject/usegalaxy-playbook/issues/102

### Tutorials

- [ ] **Mothur GTN tutorial** 5/29: ready to test against updated tools/datatypes. https://github.com/galaxyproject/usegalaxy-playbook/issues/74

### VCF datasets/tools

- [ ] **Test VCF Mani tools** Older versions displayed from tool menu with no warning that a newer version if available. Some older versions buggy/shouldn't be used. https://github.com/galaxyproject/galaxy/issues/3021 && https://github.com/galaxyproject/tools-devteam/issues/391
- [ ] **VCFFilter** Needs the tool help updated to reflect the new form structure plus requested clearer error messages for commonly reported bugs (nearly all are malformed filter terms, we can catch those). https://github.com/galaxyproject/tools-iuc/issues/1910

###  Upload && Get Data

- [x] **EBI SRA** incorrectly assigns "fastqsanger" to "fastqsanger.gz" outputs. Also, if the data is really in "fastqcssanger.gz" format, it is assigned "fastqsanger" https://github.com/galaxyproject/galaxy/issues/6334
- [ ] **Get Data tools meta change** - Data Source Tool: Don't use output as config file https://github.com/galaxyproject/galaxy/issues/6245
 - [ ] **Upload** duplicate dataset name problem https://github.com/galaxyproject/galaxy/issues/6138
 - [x] **CONVERTER_interval_to_bed_0** - fails during upload (when envoked) and when using Edit Attributes > Convert. https://github.com/galaxyproject/galaxy/issues/6379

### Datasets

 - [ ] **Dataset links** - Old links to datasets no longer work. Example: datasets included in UCSC Sessions. New persistent links are planned for, but how older links if/will remain functional is TBD Ticket: provide persistent links to all shareable Galaxy objects https://github.com/galaxyproject/galaxy/issues/6645

###  Collections 

 - [ ] **Collection download problems**.  @martenson creating new issue for https://github.com/galaxyproject/usegalaxy-playbook/issues/85#issuecomment-369390850 make sure linked and close out https://github.com/galaxyproject/usegalaxy-playbook/issues/85. 
 - [ ] **Collection filters/functions** test once implimented. Tickets https://github.com/galaxyproject/galaxy/issues/5090 (empty datasets) & https://github.com/galaxyproject/galaxy/issues/2496 (many enhancements)
- [ ] **Retest deleted collection datasets** https://github.com/galaxyproject/galaxy/issues/5402

###  Workflows 

- [ ] **Workflow extraction problems** on main https://github.com/galaxyproject/usegalaxy-playbook/issues/109 links to https://github.com/galaxyproject/usegalaxy-playbook/issues/99
- [ ] **Workflow extraction issues** related to manually unhidden datasets and certain tools plus a bad GUI link: https://github.com/galaxyproject/usegalaxy-playbook/issues/99
- [ ] **Deleting a workflow does not remove it from the Tool Panel (when pinned)** https://github.com/galaxyproject/galaxy/issues/5318
 - [ ] Test **Workflow Editor tool search box missing clear / closing X** once fixed https://github.com/galaxyproject/galaxy/issues/5671
- [ ] **Retest workflow collection/Inputs problems** after fixed: https://github.com/galaxyproject/galaxy/issues/5632
- [ ] **Retest workflows version conflicts resulting in dropped input connections** after fixed https://github.com/galaxyproject/galaxy/issues/5554
 - [ ] **Retest workflow custom genome selection** Is from 2015 - might be fixed already https://github.com/galaxyproject/galaxy/issues/1132

###  Tools

- [ ] Retest **Diffbind 2.6.6.4** https://github.com/galaxyproject/usegalaxy-playbook/issues/127. 9/6/18 retest in progress
 - [ ] Update **Featurecounts** once ready (usage fixes) https://github.com/galaxyproject/usegalaxy-playbook/issues/139
 - [ ] Update **RNA STAR 2.5.2b-0** database assignment fix, all outputs https://github.com/galaxyproject/usegalaxy-playbook/issues/134
- [ ] Related to **RNA-star upgrade** there is one common usage issue that *might* be addressed in the new version. Ticket to check/ask about tool form enhancement was created here: https://github.com/galaxyproject/tools-iuc/issues/1777 
- [ ] **Mpileup** will need an update once corrected and in MTS https://github.com/galaxyproject/usegalaxy-playbook/issues/133
- [ ] **Circos** graph problems. Tool needs fix then update on main. Ticketed #105 (.org) and https://github.com/galaxyproject/tools-iuc/issues/1919 (iuc fix request)
- [ ] **MAF tools errors**: header only "green" empty datasets + python failures for simple queries. https://github.com/galaxyproject/usegalaxy-playbook/issues/130
- [ ]  **Join two Datasets** (Galaxy Version 2.1.1) -- incorrectly inherits 1st inputs datatype https://github.com/galaxyproject/galaxy/issues/6107
 - [ ]  **MultiQC** does not recognize raw data (txt) from FastQC when in a collection https://github.com/galaxyproject/usegalaxy-playbook/issues/114
 - [ ] **MultiQC** Version 1.2.0 does not include this yet but looks like it might in the next rev: Enhancement to filter inputs better (MultiQC should not accept HTML/graphics inputs - just text/tabular). As part of this, output more informative FastQC output datatype/dataset names to prevent users from choosing incorrect inputs. Details include followed up on 3/2/18: https://github.com/galaxyproject/tools-iuc/issues/1538
- [ ] **Check/Test if compressed inputs work with these tools**, if now on main https://github.com/galaxyproject/usegalaxy-playbook/issues/67
- [ ] **Freebayes in the tool panel twice (unassociated tool wrappers)** https://github.com/galaxyproject/usegalaxy-playbook/issues/108
 - [ ] **SnpEff** Update/add sub-tools, fixes an important bug https://github.com/galaxyproject/usegalaxy-playbook/issues/157 
 - [ ] **Test Cuffdiff update once on main**. Update: v 2.2.1.5 SQLite option is a problem, prior version had the same problem but we fixed it server-side. https://github.com/galaxyproject/usegalaxy-playbook/issues/50#issuecomment-368126861
- [ ] **Enhance job errors for HISAT2 and Bowtie2**. Will need main update ticket if/once done. https://github.com/galaxyproject/tools-iuc/issues/1789 && https://github.com/galaxyproject/tools-iuc/issues/1790. @mvdbeek thinks this isn't need so we closed out. Watch bug reports going forward to see if this actually comes up for end-users. **Update** Might be opened again, mapping stats reports input problem but results are still green/success (BAM only contains the header) - plus rerun/switching tool versions (Bowtie 2.2.6.2 > 2.3.4.1) brings up hidden datasets as the default select. Different problem, may need a ticket: https://github.com/galaxyproject/tools-iuc/issues/1789#issuecomment-377431536

###  FAQs

 - [ ] Update **Hub FAQs for FTP-loading and link to Troubleshooting** to address actively transferring FTP loads listed in Upload/FTP staging GUI. Details: https://github.com/galaxyproject/usegalaxy-playbook/issues/103#issuecomment-394802513
 - [ ] Update **Hub FAQs to include this example for NCBI fasta download/upload**. Biostars/graphics links in test history: https://usegalaxy.org/u/jen/h/test-history-ncbi-fasta-download-ftp-upload
 - [ ] **Update getgalaxy.org** section for "how to become admin" with the yml config

###  General

- [ ] **Galaxy start-up loops**, known or fixed or wip? https://biostar.usegalaxy.org/p/27255/ and asked team here https://gitter.im/galaxyproject/committers?at=5ab5aa5bfa066c5325657e83
- [ ] Test **Tools with optional output dataset directories fail if the directory does not exist** once 18.01 updated on Main https://github.com/galaxyproject/galaxy/issues/5560
- [ ] Test **Dynamically Generated Tool Parameters cannot be set until dataset has finished()** once updated https://github.com/galaxyproject/galaxy/issues/3758

###  Enhancements

- [ ] Enhancement: **Enable tag/anno edits for queued, executing, failed jobs** https://github.com/galaxyproject/galaxy/issues/6330
- [ ] **Wokflow share link view** Modify GUI to offer links for "run, edit, save" and remove "import" when a shared workflow is already owned by the same user https://github.com/galaxyproject/galaxy/issues/6250
- [ ] **History** GUI ideas including dataset "map" view https://github.com/jennaj/support-known-issues/wiki/History-usability-ideas
- [ ] **Workflows** When a workflow is sent to a new history, that history link is not in the "launched" message anymore https://github.com/galaxyproject/galaxy/issues/6167. **6/18 Added bacl, update to main pending.**
 - [ ] Followup **Active index selection on tools**. Mapping tools https://github.com/galaxyproject/galaxy/issues/4499 
 - [ ] **Tool version in UI: enhancement** https://github.com/galaxyproject/galaxy/projects/8#card-7647616 & https://github.com/galaxyproject/galaxy/issues/5592
- [ ] **GUI improvement ideas** (some already done, some potentials for future) https://github.com/jennaj/support-known-issues/wiki/Enhancements

###  Other items

All here need follow-up/tickets: https://github.com/galaxyproject/usegalaxy-playbook/issues/94

**Comment by jennaj** [comment]
Priority -- tool updates https://github.com/galaxyproject/usegalaxy-playbook/commit/34a4dd4815981e23ec7f3a436048cf990c3146ce
update Main's tools

- [ ] remove all of anton's vcflib tools (were hidden)
- [ ] remove all versions of vcffilter
- [ ] update bamtools
- [ ] update Deseq2
- [ ] update bowtie2
- [ ] update samtool_filter2
- [ ] update xy_plot
- [ ] update sra_tools: Exact BAM works, testing others.
- [ ] update fastq_paired_end
- [ ] install star_fusion
- [ ] update stringtie
- [ ] update featurecounts
- [ ] update bwa: In progress.

**Comment by jennaj** [comment]
- [ ] Mothur tools updated, needs a test run through the complete 16S tutorial. Includes other changes/updated captured here: https://github.com/galaxyproject/usegalaxy-playbook/issues/74

**Comment by jennaj** [comment]
See the project instead https://github.com/galaxyproject/usegalaxy-playbook/projects/1
